version: '3.4'
name: my-task-tracker-backend
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ../frontend/static:/data/static:ro
      - ./log:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ../backend/
    env_file:
      ../backend/.env
    expose:
      - 8000
    depends_on:
      - postgres
    command: sh -c ../backend-entrypoint.sh
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      .env.db
    environment:
      PGDATA: "var/lib/postgresql/data/"
    expose:
      - 5432
    volumes:
      - .docker-volumes/postgres/data:/var/lib/postgresql/data/
    restart: unless-stopped
