# Generated by Django 4.1.7 on 2023-03-03 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="section",
            field=models.ForeignKey(
                limit_choices_to={"user": models.F("user")},
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.tasksection",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                limit_choices_to={"user": models.F("user")},
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.taskstatus",
            ),
        ),
    ]
