# Generated by Django 4.1.7 on 2023-03-04 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_due_datetime_alter_task_section_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.SmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
